freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  env:
    CIRRUS_CLONE_DEPTH: 1
    MAKE_FLAGS: -j 4
  
  install_script:
    - sudo pkg install -y autoconf automake libtool pkgconf sqlite3 tiff gmake curl
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm --installdeps --notest Alien::proj
    - sudo cpanm Alien::curl

  script:
    - perl Makefile.PL
    - sudo cpanm --installdeps .
    - make
    - make test
