freebsd_instance:
  image_family: freebsd-12-2

task:
  env:
    CIRRUS_CLONE_DEPTH: 1
    MAKE_FLAGS: -j 4
  
  install_script:
    - sudo pkg install -y pkgconf sqlite3 tiff gmake curl cmake
    - sudo pkg install -y perl5 p5-App-cpanminus
    #- sudo cpanm --installdeps .
    - sudo cpanm Data::Dump
    - sudo cpanm Alien::Build::Plugin::PkgConfig::PPWrapper
    - sudo cpanm --installdeps --notest Alien::proj
    - sudo cpanm Alien::curl
    - sudo cpanm Alien::libtiff

  script:
    - perl Makefile.PL
    - sudo cpanm --installdeps .
    - make
    - make test
